#ifndef __MAPS_SBG_OUTPUT_TYPES_H__
#define __MAPS_SBG_OUTPUT_TYPES_H__

#include "sbgEComLib.h"

//sbgECom for Ellipse series.

inline const char* sbgEcomLogToString(SbgEComClass value)
{
#define SBG_ECOM_LOG_TO_STRING_CASE_HELPER(value) case value: return #value;
    switch (value)
    {
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_STATUS)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_UTC_TIME)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_IMU_DATA)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_MAG)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_MAG_CALIB)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_EKF_EULER)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_EKF_QUAT)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_EKF_NAV)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_SHIP_MOTION)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_GPS1_VEL)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_GPS1_POS)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_GPS1_HDT)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_GPS2_VEL)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_GPS2_POS)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_GPS2_HDT)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_ODO_VEL)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_EVENT_A)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_EVENT_B)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_EVENT_C)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_EVENT_D)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_EVENT_E)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_DVL_BOTTOM_TRACK)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_DVL_WATER_TRACK)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_GPS1_RAW)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_SHIP_MOTION_HP)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_AIR_DATA)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_USBL)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_GPS2_RAW)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_IMU_SHORT)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_EVENT_OUT_A)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_EVENT_OUT_B)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_DEPTH)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_DIAG)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_RTCM_RAW)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_GPS1_SAT)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_GPS2_SAT)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_EKF_ROT_ACCEL_BODY)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_EKF_ROT_ACCEL_NED)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_EKF_VEL_BODY)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_SESSION_INFO)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_EKF_DEBUG)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_PTP_STATUS)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_VELOCITY_1)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_VIB_MON_FFT)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_VIB_MON_REPORT)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_EKF_AIR_DATA)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_POSITION_1)
        SBG_ECOM_LOG_TO_STRING_CASE_HELPER(SBG_ECOM_LOG_ECOM_NUM_MESSAGES)
    }
    return "Unknown";
}
//WARNING: alignment is not set to 1 with #pragma pack etc. as it would require modifiying and recompmiling
//the SbgECom lib for all data structures.
//So recordings and streamed data will not be compatible between Windows and Linux.
typedef struct SbgEComData
{
	SbgEComClass cmd;
	SbgBinaryLogData logdata;
} SbgEComData;

const MAPSTypeFilterBase MAPSFilterSbgEComData = MAPSFilterUserStructure(SbgEComData);
#endif //__MAPS_SBG_OUTPUT_TYPES_H__